###_________________########
##/////////\\\\\\\\\########
#//////////\\\\\\\\\\#######
#//// Xiavic Core \\\\######
#\\\\\ Plugin 2.0 ////######
#\\\\\\\\\\//////////#######
##\\\\\\\\\/////////########
###\\\\\\\\////////#########
####\\\\\\\///////##########
#####\\\\\\//////###########
######\\\\\/////############
#######\\\\////#############
#######\\_|_//##############


##############################
######## !! CONFIG !! ########
##############################

#Spawn | world name, X, Y, Z, Yaw, Pitch
Spawn_World_Name: world,100,100,100,100,100


#Economy
Balance_Check: 60

#Private Warps
PWCooldown: 300
#If set to true, players will still need the permission node.
CanShare: false

#Teleport
TpaCooldown: 5 # Time before you can send another request
Tpa_Delay: 3 # Time before actually teleporting
Tpa_Timeout: 60 # Time before the request expires

#RTP
RTPCooldown: 600
RTPWorld: world
RTPDistance: 50000

#Life
HealCooldown: 600
FeedCooldown: 600

#Near Max-Distance
NearRange: 1000

